- name: Playbook para prueba de collection aws
  hosts: localhost
  tasks:
    - name: Tarea de prueba
      community.aws.ec2_vpc_vgw_info:
        region: ap-southeast-2
        profile: production
      register: vgw_info
