- hosts: localhost
  tasks:
    - name: Evaluate Security group rules from EC2 instance to RDS Instance
      cloud.aws_ops.validate_security_group_rules:
        dest_subnet_cidrs:
            - 10.1.0.0/24
            - 10.1.2.0/24
        dest_security_groups:
            - description: "Security group for EC2 instance"
              group_id: "sg-0bd2d9a14af754812"
              group_name: "aubin-sg"
              ip_permissions:
                - from_port: 5432
                  to_port: 5432
                  ip_protocol: "tcp"
                  ip_ranges":
                    - cidr_ip: "0.0.0.0/0"
                  ipv6_ranges: []
                  prefix_list_ids: []
                  user_id_group_pairs: []
              ip_permissions_egress:
                - ip_protocol": -1
                  ip_ranges:
                    - cidr_ip: "0.0.0.0/0"
                  ipv6_ranges: []
                  prefix_list_ids: []
                  user_id_group_pairs: []
              owner_id: "0000000000000"
              vpc_id: "vpc-0bee28efef41e1de4"
        dest_port: 5432
        src_security_groups:
            - description: "Security group for EC2 instance"
              group_id: "sg-0bd2d9a14af8a8998"
              group_name: "aubin-sg"
              ip_permissions:
                - from_port: 22
                  to_port: 22
                  ip_protocol: "tcp"
                  ip_ranges":
                    - cidr_ip: "0.0.0.0/0"
                  ipv6_ranges: []
                  prefix_list_ids: []
                  user_id_group_pairs: []
              ip_permissions_egress:
                - ip_protocol": -1
                  ip_ranges:
                    - cidr_ip: "0.0.0.0/0"
                  ipv6_ranges: []
                  prefix_list_ids: []
                  user_id_group_pairs: []
              owner_id: "0000000000000"
              vpc_id: "vpc-0bee28efef41e1de4"
        src_private_ip: "172.10.3.10"
