- hosts: localhost
#  tasks:
#    - name: Log in (obtain access token)
#      redhat.openshift.openshift_auth:
#        username: admin
#        password: admin
#      register: openshift_auth_results
#

  roles:
#    - role: ../requirements_collections/ansible_collections/bac/windows/roles/miprueba/
    - role: bac.windows.miprueba
      nombre: Gary
