- hosts: localhost
#  tasks:
#    - name: Log in (obtain access token)
#      redhat.openshift.openshift_auth:
#        username: admin
#        password: admin
#      register: openshift_auth_results
#
  pre_tasks:
  - name: Pause for 5 minutes to build app cache
    ansible.builtin.pause:
      minutes: 5
  roles:
    - role: ../requirements_collections/ansible_collections/bac/windows/roles/mi_prueba
      nombre: Gary
