- hosts: localhost
#  tasks:
#    - name: Log in (obtain access token)
#      redhat.openshift.openshift_auth:
#        username: admin
#        password: admin
#      register: openshift_auth_results
#

  roles:
    - role: mi_prueba
      nombre: Gary
